# KiCad .gitignore generator

# Run from the PCB editor via Tools -> External Plugins -> Generate Gitignore.

# Author: Alex Ren
# License: MIT
# Repository: https://github.com/qcoral/kicad-gitignore


import os
import pcbnew
import wx


KICAD_GITIGNORE = """\
# Auto-generated by kicad-gitignore - https://github.com/qcoral/kicad-gitignore
# Based on: https://github.com/github/gitignore/blob/main/KiCad.gitignore

# Temp files
*.000
*.bak
*.bck
*.kicad_pcb-bak
*.kicad_sch-bak
*-backups
*-cache*
*-bak
*-bak*
*~
~*
_autosave-*
\#auto_saved_files\#
*.tmp
*-save.pro
*-save.kicad_pcb
fp-info-cache
~*.lck
\#auto_saved_files#

# Netlist files (exported from Eeschema)
*.net

# Autorouter files (exported from Pcbnew)
*.dsn
*.ses

# Archived backups (KiCad 6.0+)
**/*-backups/*.zip

# Local project settings
*.kicad_prl

# Generated assembly outputs (uncomment if desired)
# *.csv
# *.xml

# OS files
.DS_Store
Thumbs.db
"""

def get_project_dir():
    """Get the project directory from the currently open PCB"""
    board = pcbnew.GetBoard()
    if board is None:
        return None
    board_file = board.GetFileName()
    if not board_file:
        return None
    return os.path.dirname(os.path.abspath(board_file))


def generate_gitignore(project_dir, silent=False):
    """
    Write .gitignore to the project directory.
    Returns True if created, False if skipped or failed.
    If silent=True, no dialogs are shown.
    """
    if not project_dir:
        if not silent:
            wx.MessageBox(
                "Could not determine the project directory.\n"
                "Make sure a board file is open and saved.",
                ".gitignore generator",
                wx.OK | wx.ICON_WARNING,
            )
        return False

    gitignore_path = os.path.join(project_dir, ".gitignore")

    if os.path.exists(gitignore_path):
        if not silent:
            wx.MessageBox(
                f".gitignore already exists in:\n{project_dir}\n\n"
                "No changes were made.",
                ".gitignore generator",
                wx.OK | wx.ICON_INFORMATION,
            )
        return False

    try:
        with open(gitignore_path, "w", encoding="utf-8") as f:
            f.write(KICAD_GITIGNORE)
    except OSError as e:
        if not silent:
            wx.MessageBox(
                f"Failed to write .gitignore:\n{e}",
                ".gitignore generator",
                wx.OK | wx.ICON_ERROR,
            )
        return False

    if not silent:
        wx.MessageBox(
            f"Created .gitignore in:\n{project_dir}",
            ".gitignore generator",
            wx.OK | wx.ICON_INFORMATION,
        )
    return True


class GitignoreGeneratorPlugin(pcbnew.ActionPlugin):
    def defaults(self):
        self.name = "Generate .gitignore"
        self.category = "Project Setup"
        self.description = (
            "Generate a .gitignore file for this KiCad project"
        )
        icon_path = os.path.join(os.path.dirname(__file__), "git-icon-1788c-24px.png")
        self.show_toolbar_button = True
        if os.path.exists(icon_path):
            self.icon_file_name = icon_path

    def Run(self):
        project_dir = get_project_dir()
        generate_gitignore(project_dir, silent=False)


GitignoreGeneratorPlugin().register()